Medichain/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('',include('core.urls')),
    path('parties/',include('parties.urls')),
    path("admin/", admin.site.urls),
    path('chain/', include('chain.urls')),
    path('auth_server/', include('auth_server.urls')),
]

auth_server/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "auth_server"

urlpatterns = [
    path('',views.token_detail, name='verify'),
    path('download/<str:path>/', views.download_file, name='download_file'),] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

]

auth_server/models.py
from django.db import models

# Create your models here.

auth_server/views.py
from django.shortcuts import render

from django.utils import timezone
from chain.models import Token
from django.http import HttpResponse
import os
from django.conf import settings
import os
from chain.views import contract



def token_detail(request):
    if request.method == 'POST':
        token_number = request.POST['token_number']
        expiry_date = request.POST['expiry_date']
        try:
            token = Token.objects.get(token=token_number, expiry_date=expiry_date)
            token_valid = True
        except Token.DoesNotExist:
            token_valid = False
            token = None

        if token_valid:
            # Fetch the token using the getToken function of the contract instance
            signature = token.signature
            receiver = token.receiver
            fetched_token = contract.functions.getToken(signature, receiver)

            # Perform verification logic with the fetched_token
            
            # Add the verification result to the context dictionary
            context = {
                'token': token,
                'token_valid': token_valid,
                'fetched_token': fetched_token,
                'error': None
            }
        else:
            context = {
                'token': token,
                'token_valid': token_valid,
                'fetched_token': None,
                'error': 'Invalid token or expiry date. Please try again.'
            }

        return render(request, 'auth_server/verify.html', context)
    else:
        return render(request, 'auth_server/verify.html')



def download_file(request, path):
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    with open(file_path, 'rb') as fh:
        response = HttpResponse(fh.read(), content_type="application/octet-stream")
        response['Content-Disposition'] = 'attachment; filename=' + os.path.basename(file_path)
        return response

auth_server/templates/auth_server/verify.html
{% extends 'core/base.html' %}
{% block title %}verify token{% endblock %}

{% block content %}
  <div class="mx-auto my-10 p-10 w-1/2">
    <h1 class="text-3xl font-bold mb-4">Verify Token</h1>
    
    <form class="my-6" method="post" action="{% url 'auth_server:verify' %}">
      {% csrf_token %}
      <div class="mb-4">
        <label class="block text-gray-700 font-bold mb-2" for="token_number">
          Token Number
        </label>
        <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="token_number" type="text" name="token_number" required>
      </div>
      <div class="mb-4">
        <label class="block text-gray-700 font-bold mb-2" for="expiry_date">
          Expiry Date
        </label>
        <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="expiry_date" type="date" name="expiry_date" required>
      </div>
      <div class="flex items-center justify-between">
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
          Verify
        </button>
      </div>
    </form>
    {% if error %}
      <p class="text-red-500 font-bold">{{ error }}</p>
    {% elif token_valid %}
      <a href="{% url 'auth_server:download_file' path='data.txt' %}" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded cursor-pointer">Download</a>
    {% endif %}
  </div>
{% endblock %}