Medichain/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('',include('core.urls')),
    path('parties/',include('parties.urls')),
    path("admin/", admin.site.urls),
    path('chain/', include('chain.urls')),
    path('auth_server/', include('auth_server.urls')),
]

chain/urls.py
from django.urls import path
from . import views

app_name = "chain"

urlpatterns = [
    path("request-form/", views.request_form, name="request_form"),
    path("request-list/", views.request_list, name="request_list"),
    path('', views.create_token, name='create_token'),
    path('tokens/', views.token_list, name='token_list'),
    path('token-created/',views.token_created, name='token_created'),
    path('request-sent',views.request_sent, name="request_sent"),

]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

]

chain/models.py
from django.db import models

# Create your models here.
from django.db import models

class Request(models.Model):
    Rqp_name = models.CharField(max_length=100)
    Ds_name = models.CharField(max_length=100)
    timestamp = models.DateTimeField(auto_now_add=True)

class Token(models.Model):
    signature = models.CharField(max_length=100)
    receiver = models.CharField(max_length=100)
    token = models.CharField(max_length=100)
    expiry_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.signature} - {self.receiver} - {self.token} - {self.expiry_date}"

chain/forms.py
from django import forms
 

from .models import Request,Token
from django.contrib.auth import get_user_model
import random
import datetime

User = get_user_model()
data_subjects = User.objects.filter(Data_Subject=True)



class RequestForm(forms.ModelForm):
    Ds_name = forms.ChoiceField(
        choices=[(user.username, user.username) for user in data_subjects], 
        widget=forms.Select(attrs={'class': 'w-full bg-gray-100 p-3 rounded-lg'}),
    )    
    class Meta:
        model = Request
        fields = ['Rqp_name', 'Ds_name']
        widgets = {
            'Rqp_name': forms.TextInput(attrs={'placeholder': 'Requesting Party', 'class': 'w-full bg-gray-100 p-3 rounded-lg mb-4'}),
        }





'''
class TokenForm(forms.ModelForm):
    expiry_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

    class Meta:
        model = Token
        fields = ['signature', 'receiver', 'token', 'expiry_date']  
        widgets = {
            'signature': forms.TextInput(attrs={'placeholder': 'Signature','class': 'w-full py-4 px-6 rounded-xl'}),
            'receiver': forms.TextInput(attrs={'placeholder': 'Receiver','class': 'w-full py-4 px-6 rounded-xl'}),
            'token': forms.TextInput(attrs={'placeholder': 'Token','class': 'w-full py-4 px-6 rounded-xl'}),
        }      '''



class TokenForm(forms.ModelForm):
    expiry_choices = [('1 Week', '1 Week'), ('1 Month', '1 Month'), ('3 Months', '3 Months')]
    expiry_date_choice = forms.ChoiceField(choices=expiry_choices)

    class Meta:
        model = Token
        fields = ['signature', 'receiver']

    def clean_expiry_date_choice(self):
        expiry_date_choice = self.cleaned_data['expiry_date_choice']
        if expiry_date_choice == '1 Week':
            expiry_date = datetime.date.today() + datetime.timedelta(weeks=1)
        elif expiry_date_choice == '1 Month':
            expiry_date = datetime.date.today() + datetime.timedelta(days=30)
        elif expiry_date_choice == '3 Months':
            expiry_date = datetime.date.today() + datetime.timedelta(days=90)
        return expiry_date

    def save(self, commit=True):
        token = str(random.randint(0, 9999))
        expiry_date = self.clean_expiry_date_choice()
        instance = super().save(commit=False)
        instance.token = token
        instance.expiry_date = expiry_date
        if commit:
            instance.save()
        return instance

chain/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from .forms import RequestForm, TokenForm
from .models import Request, Token
from django.core.mail import send_mail
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth import get_user_model
from parties.models import User
from django.conf import settings
from django.shortcuts import render, get_object_or_404
from django.views import View
import random
# web3 imports
import json
from web3 import Web3

PUBLIC_KEY = "0xE71115Ed8904541C08DeCB032877e2D85f527e61"
PRIVATE_KEY = "ad601d0aee9345d7c1891c2b722f6c1bec9fbc51ddc4a646daa83566eb7da427"

URL = "HTTP://127.0.0.1:8545"

web3 = Web3(Web3.HTTPProvider(URL))

address = Web3.toChecksumAddress("0xd8D2Af9EDB2186CDce2d7371bEabC9298043C97d")

contract_abi = """[
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": false,
				"internalType": "string",
				"name": "signature",
				"type": "string"
			},
			{
				"indexed": false,
				"internalType": "string",
				"name": "receiver",
				"type": "string"
			},
			{
				"indexed": false,
				"internalType": "string",
				"name": "token",
				"type": "string"
			}
		],
		"name": "NewToken",
		"type": "event"
	},
	{
		"inputs": [
			{
				"internalType": "string",
				"name": "signature",
				"type": "string"
			},
			{
				"internalType": "string",
				"name": "receiver",
				"type": "string"
			},
			{
				"internalType": "string",
				"name": "token",
				"type": "string"
			}
		],
		"name": "saveToken",
		"outputs": [
			{
				"internalType": "bool",
				"name": "",
				"type": "bool"
			}
		],
		"stateMutability": "payable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "string",
				"name": "signature",
				"type": "string"
			},
			{
				"internalType": "string",
				"name": "receiver",
				"type": "string"
			}
		],
		"name": "getToken",
		"outputs": [
			{
				"internalType": "string",
				"name": "",
				"type": "string"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "",
				"type": "address"
			}
		],
		"name": "signToToken",
		"outputs": [
			{
				"internalType": "string",
				"name": "",
				"type": "string"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"name": "tokens",
		"outputs": [
			{
				"internalType": "string",
				"name": "signature",
				"type": "string"
			},
			{
				"internalType": "string",
				"name": "receiver",
				"type": "string"
			},
			{
				"internalType": "string",
				"name": "token",
				"type": "string"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"name": "tokenToOwner",
		"outputs": [
			{
				"internalType": "address",
				"name": "",
				"type": "address"
			}
		],
		"stateMutability": "view",
		"type": "function"
	}
]"""
abi = json.loads(contract_abi)


contract = web3.eth.contract(address=address, abi=abi)

web3.eth.defaultAccount = web3.eth.accounts[0]


def SaveToken(signature, receiver, token):
    # Send a transaction to save a new token
    tx_hash = contract.functions.saveToken(signature, receiver, token).transact()
    web3.eth.waitForTransactionReceipt(tx_hash)

    print("Transaction confirmed!")


def GetToken(signature, receiver):
    # Call the getToken function
    result = contract.functions.getToken(signature, receiver).call()
    print(result)


def request_form(request):
    if request.method == "POST":
        form = RequestForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('chain:request_sent')
    else:
        form = RequestForm()
    return render(request, "chain/request_form.html", {"form": form})


def request_list(request):
    # Retrieve all the requests that match the Ds_name of the logged-in user
    requests = Request.objects.filter(Ds_name=request.user.username)

    context = {
        'requests': requests
    }

    return render(request, 'chain/request_list.html', context)

'''class RequestDetailView(View):
    def get(self, request, pk):
        # get the request object based on the pk
        request_obj = get_object_or_404(Request, pk=pk)
        
        # get the next and previous requests
        next_request = Request.objects.filter(pk__gt=pk, Ds_name=request_obj.Ds_name).order_by('pk').first()
        prev_request = Request.objects.filter(pk__lt=pk, Ds_name=request_obj.Ds_name).order_by('-pk').first()

        context = {
            'request': request_obj,
            'next_request': next_request,
            'prev_request': prev_request,
        }
        return render(request, 'chain/request_detail.html', context)'''

def create_token(request):
    if request.method == 'POST':
        form = TokenForm(request.POST)
        if form.is_valid():
            # Create a new Token object from the form data
            signature = form.cleaned_data['signature']
            receiver = form.cleaned_data['receiver']
            token = str(random.randint(0, 9999))
            expiry_date = form.cleaned_data['expiry_date_choice']
            user = User.objects.get(username=receiver)
            email = user.email
            token_obj = Token(signature=signature, receiver=receiver, token=token, expiry_date=expiry_date)
            token_obj.save()
            

            # Send a transaction to save a new token
            tx_hash = contract.functions.saveToken(signature, receiver, token).transact()
            web3.eth.waitForTransactionReceipt(tx_hash)
            
			
            print("Transaction confirmed!")
            send_mail('Token is created', str(token_obj), 'settings.EMAIL_HOST_USER', [email])
            return redirect('chain:token_created')
    else:
        form = TokenForm()

    return render(request, 'chain/create_token.html', {'form': form})

def token_list(request):
    tokens = Token.objects.all()

    context = {
        'tokens': tokens
    }

    return render(request, 'chain/token_list.html', context)

def token_created(request):
    return render(request, 'chain/token_created.html')

def request_sent(request):
    return render(request, 'chain/request_sent.html')


        

chain/templates/chain/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    {% block content %}
    {% endblock %}
  </body>
</html>

chain/templates/chain/create_token.html
{% extends 'core/base.html' %}

{% block title %}Create Token{% endblock %}

{% block content %}
  <h1 class="text-2xl font-bold mb-8">Create Token</h1>
  <form method="post" class="max-w-md mx-auto bg-white p-6 rounded-lg shadow-lg">
    {% csrf_token %}
    <div class="mb-4 bg-gray-100 p-4 rounded-lg flex flex-wrap items-center">
      <label for="{{ form.signature.id_for_label }}" class="block font-bold mb-2 mr-4">Signature:</label>
      {{ form.signature }}
    </div>
    <div class="mb-4 bg-gray-100 p-4 rounded-lg flex flex-wrap items-center">
      <label for="{{ form.receiver.id_for_label }}" class="block font-bold mb-2 mr-4">Receiver:</label>
      {{ form.receiver }}
    </div>
    <div class="mb-4 bg-gray-100 p-4 rounded-lg flex flex-wrap items-center">
      <label for="{{ form.expiry_date_choice.id_for_label }}" class="block font-bold mb-2 mr-4">Expiry Date:</label>
      {{ form.expiry_date_choice }}
    </div>
    <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
      Create
    </button>
  </form>
{% endblock %}

chain/templates/chain/request_form.html
{% extends 'core/base.html' %}

{% block content %}
<div class="border rounded p-4">
    <h1 class="text-2xl font-bold">Request Form</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="bg-blue-500 text-white font-bold py-2 px-4 rounded mt-4">Submit</button>
    </form>
</div>
{% endblock %}

chain/templates/chain/request_list.html
{% extends 'core/base.html' %}

{% block title %}View Requests{% endblock %}
{% block content %}
  <div class="bg-gray-100">
    <div class="max-w-7xl mx-auto py-12 sm:px-6 lg:px-8">
      <div class="px-4 sm:px-0">
        <h1 class="text-3xl font-bold mb-8">View requests</h1>
        {% if requests %}
          <ul class="divide-y divide-gray-200">
            {% for request in requests %}
              <li class="py-4 flex justify-between items-center">
                <div class="flex-1 min-w-0">
                  <p class="text-sm font-medium text-gray-900 truncate">{{ request.Rqp_name }} - {{ request.Ds_name }} - {{ request.timestamp }}</p>
                </div>
                <div class="ml-4 flex-shrink-0">
                  <a href="{% url 'chain:create_token'%}" class="px-3 py-1 border border-transparent text-sm font-medium rounded-md text-white bg-green-500 hover:bg-green-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500">Approve Request</a>
                </div>
              </li>
            {% empty %}
              <li class="py-4">
                <p class="text-sm font-medium text-gray-900 truncate">No requests yet.</p>
              </li>
            {% endfor %}
          </ul>
        {% else %}
          <p class="text-lg font-medium text-gray-900">No requests yet.</p>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

chain/templates/chain/request_sent.html
{% extends 'core/base.html' %}

{% block title %}Request is Sent{% endblock %}
{% block content %}

<body>
    <div style="position: relative; width: 100%; height: 0; padding-top: 56.2500%;
    padding-bottom: 0; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden;
    border-radius: 8px; will-change: transform;">
     <iframe loading="lazy" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"
       src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAFjq8oh9vY&#x2F;view?embed" allowfullscreen="allowfullscreen" allow="fullscreen">
     </iframe>
   </div>
</body>
{% endblock %}

chain/templates/chain/token_created.html
{% extends 'core/base.html' %}

{% block title %}Token Created{% endblock %}
{% block content %}

<body>
    <div style="position: relative; width: 100%; height: 0; padding-top: 56.2500%;
 padding-bottom: 0; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden;
 border-radius: 8px; will-change: transform;">
  <iframe loading="lazy" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"
    src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAFjPlKL2lw&#x2F;view?embed" allowfullscreen="allowfullscreen" allow="fullscreen">
  </iframe>
</div>
</body>
{% endblock %}

chain/templates/chain/token_list.html
{% extends 'chain/base.html' %}

{% block title %}
  Token List
{% endblock %}

{% block content %}
  <h1>Token List</h1>
  <table>
    <thead>
      <tr>
        <th>Signature</th>
        <th>Receiver</th>
        <th>Token</th>
        <th>Expiry Date</th>
        <th>Created At</th>
      </tr>
    </thead>
    <tbody>
      {% for token in tokens %}
      <tr>
        <td>{{ token.signature }}</td>
        <td>{{ token.receiver }}</td>
        <td>{{ token.token }}</td>
        <td>{{ token.expiry_date }}</td>
        <td>{{ token.created_at }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}